/**
 * PDF Parser — extracts org details from a sample weekly report PDF.
 * Uses pdfjs-dist to read the first and last pages and pull:
 *   reportTitle, subtitle, preparedBy, supervisor, projectsLabel, footer
 */

let _lib = null
async function lib() {
  if (_lib) return _lib
  _lib = await import('pdfjs-dist')
  _lib.GlobalWorkerOptions.workerSrc =
    `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${_lib.version}/pdf.worker.min.mjs`
  return _lib
}

/** Extract all text items from a page, sorted top→bottom, left→right. */
async function pageItems(page) {
  const vp = page.getViewport({ scale: 1 })
  const tc = await page.getTextContent()
  return tc.items
    .filter(i => i.str?.trim())
    .map(i => {
      const [sx, , , sy, tx, ty] = i.transform
      return {
        text: i.str.trim(),
        x: tx,
        // Convert from PDF bottom-up coords to top-down
        y: vp.height - ty,
        fontSize: Math.abs(sy) || Math.abs(sx),
      }
    })
    .sort((a, b) => a.y - b.y || a.x - b.x)
}

/**
 * Merge items that are on the same line (within 3pt of each other) into
 * logical lines, left to right.
 */
function mergeToLines(items) {
  const lines = []
  for (const item of items) {
    const existing = lines.find(l => Math.abs(l.y - item.y) < 3)
    if (existing) {
      existing.text += ' ' + item.text
      existing.maxSize = Math.max(existing.maxSize, item.fontSize)
      existing.minX = Math.min(existing.minX, item.x)
    } else {
      lines.push({ text: item.text, y: item.y, maxSize: item.fontSize, minX: item.x })
    }
  }
  return lines
}

/**
 * Extract org details from a single sample PDF URL.
 * Returns null if the file doesn't exist or can't be parsed.
 */
export async function extractOrgDetails(url) {
  const pdfjs = await lib()

  let pdf
  try {
    pdf = await pdfjs.getDocument({ url, verbosity: 0 }).promise
  } catch {
    return null
  }

  // ── First page ──
  const page1 = await pdf.getPage(1)
  const items1 = await pageItems(page1)
  const lines1 = mergeToLines(items1)

  const details = {
    reportTitle:     '',
    subtitle:        '',
    preparedBy:      '',
    supervisor:      '',
    preparedByLabel: 'Prepared by',
    supervisorLabel: 'Supervisor',
    projectsLabel:   'Projects',
    footer:          '',
  }

  if (lines1.length === 0) return details

  // Title = first (largest-font or topmost) line
  details.reportTitle = lines1[0].text

  // Subtitle = second line
  if (lines1[1]) details.subtitle = lines1[1].text

  // Scan remaining lines for "Label: Value" pairs
  for (const line of lines1.slice(2)) {
    const m = line.text.match(/^([^:]+):\s*(.+)$/)
    if (!m) continue
    const label = m[1].trim()
    const value = m[2].trim()
    const labelLc = label.toLowerCase()
    if (labelLc.includes('prepared') || labelLc.includes('author')) {
      details.preparedByLabel = label
      details.preparedBy = value
    } else if (labelLc.includes('supervisor') || labelLc.includes('advisor')) {
      details.supervisorLabel = label
      details.supervisor = value
    } else if (labelLc.includes('project')) {
      details.projectsLabel = label
    }
  }

  // ── Last page footer ──
  const lastPage = await pdf.getPage(pdf.numPages)
  const itemsLast = await pageItems(lastPage)
  const linesLast = mergeToLines(itemsLast)

  if (linesLast.length > 0) {
    const lastLine = linesLast[linesLast.length - 1]
    // Footer: last line, small font, not a section heading
    if (lastLine.maxSize < 12 && lastLine.text.length > 5) {
      details.footer = lastLine.text
    }
  }

  return details
}

/**
 * Try to load the first available sample PDF from /sample-reports/.
 * Filenames: sample-report-01.pdf … sample-report-10.pdf
 */
export async function extractFromFirstSample(onProgress) {
  for (let i = 1; i <= 10; i++) {
    const name = `sample-report-${String(i).padStart(2, '0')}.pdf`
    const url  = `/sample-reports/${name}`
    try {
      const head = await fetch(url, { method: 'HEAD' })
      if (!head.ok) continue
      onProgress?.(`Parsing ${name}…`)
      const details = await extractOrgDetails(url)
      if (details) return { ...details, sourceFile: name }
    } catch {
      // continue
    }
  }
  return null
}

// ─── Report Importer ──────────────────────────────────────────────────────────

/**
 * Parse a full weekly report PDF and return a structured report object.
 * The PDF is expected to match the format generated by pdfGenerator.js.
 */
export async function importReportFromPDF(url) {
  const pdfjs = await lib()

  let pdf
  try {
    pdf = await pdfjs.getDocument({ url, verbosity: 0 }).promise
  } catch {
    return null
  }

  // Page geometry (Letter = 612 × 792 pt)
  // Header on page 1 occupies top ~185pt; running header on page 2+ ~90pt; footer ~40pt from bottom
  const HEADER_P1  = 185
  const HEADER_P2  = 90
  const FOOTER_PAD = 40

  // Collect raw items across all pages
  const allRaw = []
  for (let p = 1; p <= pdf.numPages; p++) {
    const page = await pdf.getPage(p)
    const vp   = page.getViewport({ scale: 1 })
    const tc   = await page.getTextContent()
    for (const item of tc.items) {
      if (!item.str?.trim()) continue
      const [sx, , , sy, tx, ty] = item.transform
      allRaw.push({
        text:     item.str.trim(),
        x:        tx,
        y:        vp.height - ty,   // top-down
        fontSize: Math.abs(sy) || Math.abs(sx),
        page:     p,
        pageH:    vp.height,
      })
    }
  }
  allRaw.sort((a, b) => a.page - b.page || a.y - b.y || a.x - b.x)

  // ── Header extraction (page 1 top area) ──────────────────────────────────
  const headerItems = allRaw.filter(i => i.page === 1 && i.y < HEADER_P1)
  const headerLines = mergeToLines(headerItems)

  let weekStart = '', weekEnd = '', dateLabel = '', projects = ''
  for (const line of headerLines) {
    // "Date: May 12, 2026 – May 19, 2026"
    const dm = line.text.match(/date[^:]*:\s*(.+)/i)
    if (dm) {
      dateLabel = dm[1].trim()
      const rm = dateLabel.match(/([A-Z][a-z]+ \d+,?\s*\d{4})\s*[–\-—]\s*([A-Z][a-z]+ \d+,?\s*\d{4})/i)
      if (rm) {
        try { weekStart = new Date(rm[1]).toISOString().split('T')[0] } catch { /* ok */ }
        try { weekEnd   = new Date(rm[2]).toISOString().split('T')[0] } catch { /* ok */ }
      }
    }
    const pm = line.text.match(/projects?[^:]*:\s*(.+)/i)
    if (pm) projects = pm[1].trim()
  }

  // ── Body content (skip header and footer bands) ───────────────────────────
  const bodyRaw = allRaw.filter(i => {
    const top = i.page === 1 ? HEADER_P1 : HEADER_P2
    return i.y >= top && i.y <= (i.pageH - FOOTER_PAD)
  })
  const bodyLines = mergeToLines(bodyRaw)

  const sections    = []
  let   currentSec  = null
  let   inTasks     = false
  const upcomingTasks = []

  // For tasks table: column x boundaries (PDF pts, Letter page left margin ~60pt)
  // Priority col: 60–162, Task col: 162–434, Project col: 434–552
  const TASK_X_PRIORITY = 162
  const TASK_X_PROJECT  = 434

  for (const line of bodyLines) {
    const t = line.text.trim()
    if (!t || line.maxSize < 7) continue   // skip tiny footer artefacts

    // ── Upcoming Tasks table ──────────────────────────────────────────────
    if (/^upcoming tasks$/i.test(t)) {
      if (currentSec) { sections.push(currentSec); currentSec = null }
      inTasks = true
      continue
    }

    if (inTasks) {
      // Skip column header row ("Priority  Task  Project")
      if (/^priority/i.test(t)) continue
      // Task row: starts with High / Medium / Low
      if (/^(High|Medium|Low)/i.test(t)) {
        // Re-read this line's raw items to split by column x
        const rowY   = line.y
        const rowItems = bodyRaw.filter(i => Math.abs(i.y - rowY) < 4)
        const priority = rowItems.filter(i => i.x < TASK_X_PRIORITY).map(i => i.text).join(' ').trim()
        const task     = rowItems.filter(i => i.x >= TASK_X_PRIORITY && i.x < TASK_X_PROJECT).map(i => i.text).join(' ').trim()
        const target   = rowItems.filter(i => i.x >= TASK_X_PROJECT).map(i => i.text).join(' ').trim()
        if (priority || task) {
          upcomingTasks.push({
            id:       `ti_${upcomingTasks.length}`,
            priority: priority || 'Medium',
            task:     task     || t,
            target:   target   || '',
          })
        }
      }
      continue
    }

    // ── Section heading: numbered "N. Title", larger font ────────────────
    const sh = t.match(/^(\d+)\.\s+(.+)/)
    if (sh && line.maxSize >= 13) {
      if (currentSec) sections.push(currentSec)
      currentSec = { id: `si_${sections.length}`, title: sh[2].trim(), body: '', rawNotes: '' }
      continue
    }

    // ── Body text ─────────────────────────────────────────────────────────
    if (currentSec) {
      currentSec.body += (currentSec.body ? '\n' : '') + t
    }
  }
  if (currentSec) sections.push(currentSec)

  if (!weekStart && !sections.length) return null  // nothing parsed

  return {
    id:                weekStart || `imported_${Date.now()}`,
    weekStart:         weekStart || '',
    weekEnd:           weekEnd   || '',
    dateLabel:         dateLabel || '',
    projects:          projects  || '',
    sections,
    upcomingTasks,
    targetColumnLabel: 'Project',
    attachedReports:   [],
    createdAt:         new Date().toISOString(),
    polishedAt:        sections.some(s => s.body) ? new Date().toISOString() : null,
    _imported:         true,
  }
}

/**
 * Import all sample PDFs from /sample-reports/ and return an array of report objects.
 */
export async function importAllSampleReports(onProgress) {
  const results = []
  for (let i = 1; i <= 10; i++) {
    const name = `sample-report-${String(i).padStart(2, '0')}.pdf`
    const url  = `/sample-reports/${name}`
    try {
      const head = await fetch(url, { method: 'HEAD' })
      if (!head.ok) break
      onProgress?.(`Parsing ${name}…`)
      const report = await importReportFromPDF(url)
      if (report) results.push({ ...report, _sourceFile: name })
    } catch {
      break
    }
  }
  return results
}
